version: '3'

services:
  airflow:
    image: apache/airflow:2.9.2
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
    command: >
      bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow standalone"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres-db-volume: